create database PROYECTOMSQL;

CREATE TABLE CATEGORIAS(
	ID VARCHAR(20),
	NOMBRE VARCHAR(50),
	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID)
);

CREATE TABLE DIRECTOR(
	DNI VARCHAR(10),
	NOMBRE VARCHAR(50),
	NACIONALIDAD VARCHAR(50),
	EDAD INT(3),
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI)
);

CREATE TABLE ACTORES(
	DNI VARCHAR(10),
	NOMBRE VARCHAR(50),
	NACIONALIDAD VARCHAR(50),
	EDAD INT(3),
	CONSTRAINT PK_ACTORES PRIMARY KEY (DNI)
);

CREATE TABLE USUARIO(
	ID VARCHAR(20),
	FECHA_REGISTRO DATE,
	EMAIL VARCHAR(50),
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE PAISES(
	ID VARCHAR(20),
	NOMBRE VARCHAR(50),
	IDIOMA VARCHAR(50),
	CONSTRAINT PK_PAISES PRIMARY KEY (ID)
);

CREATE TABLE SUSCRIPCION(
	ID VARCHAR(20),
	TIPO_SUS VARCHAR(50),
	PRECIO INT (4),
	ID_USU VARCHAR(20),
	CONSTRAINT PK_SUSCRIPCION PRIMARY KEY (ID),
	CONSTRAINT FK1_SUSCRIPCION FOREIGN KEY (ID_USU) REFERENCES USUARIO (ID)
);

CREATE TABLE PERFILES(
	ID VARCHAR(20),
	NOMBRE VARCHAR(50),
	PIN VARCHAR(50),
	EDAD INT(3),
	ID_USU VARCHAR(20),
	CONSTRAINT PK_PERFILES PRIMARY KEY (ID),
	CONSTRAINT FK1_PERFILES FOREIGN KEY (ID_USU) REFERENCES USUARIO (ID)
);

CREATE TABLE CONTENIDO(
	ID VARCHAR(20),
	TITULO VARCHAR(500),
	SINOPSIS VARCHAR(500),
	ANIO INT (4),
	TIPO VARCHAR(50),
	DNI_DIRE VARCHAR(10),
	CONSTRAINT PK_CONTENIDO PRIMARY KEY (ID),
	CONSTRAINT FK1_CONTENIDO FOREIGN KEY (DNI_DIRE) REFERENCES DIRECTOR (DNI)
);

CREATE TABLE GUARDAN(
	ID_CONTENIDO VARCHAR(20),
	ID_PERFILES VARCHAR(20),
	CONSTRAINT PK_GUARDAN PRIMARY KEY (ID_CONTENIDO, ID_PERFILES),
	CONSTRAINT FK1_GUARDAN FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_GUARDAN FOREIGN KEY (ID_PERFILES) REFERENCES PERFILES (ID)
);

CREATE TABLE ACTUA(
	ID_CONTENIDO VARCHAR(20),
	ID_ACTORES VARCHAR(20),
	CONSTRAINT PK_ACTUA PRIMARY KEY (ID_CONTENIDO, ID_ACTORES),
	CONSTRAINT FK1_ACTUA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_ACTUA FOREIGN KEY (ID_ACTORES) REFERENCES ACTORES (DNI)
);

CREATE TABLE VISUALIZA(
	ID_CONTENIDO VARCHAR(20),
	ID_PAISES VARCHAR(20),
	CONSTRAINT PK_VISUALIZA PRIMARY KEY (ID_CONTENIDO, ID_PAISES),
	CONSTRAINT FK1_VISUALIZA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_VISUALIZA FOREIGN KEY (ID_PAISES) REFERENCES PAISES (ID)
);

CREATE TABLE PERTENECE(
	ID_CONTENIDO VARCHAR(20),
	ID_CATEGORIAS VARCHAR(20),
	CONSTRAINT PK_PERTENECE PRIMARY KEY (ID_CONTENIDO, ID_CATEGORIAS),
	CONSTRAINT FK1_PERTENECE FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_PERTENECE FOREIGN KEY (ID_CATEGORIAS) REFERENCES CATEGORIAS (ID)
)














