INSERT INTO CATEGORIAS VALUES ('C1', 'Acción');
INSERT INTO CATEGORIAS VALUES ('C2', 'Drama');
INSERT INTO CATEGORIAS VALUES ('C3', 'Comedia');

INSERT INTO DIRECTOR VALUES ('12345678A', 'Christopher Nolan', 'Británica', 53);
INSERT INTO DIRECTOR VALUES ('87654321B', 'Pedro Almodóvar', 'Española', 74);

INSERT INTO ACTORES VALUES ('11111111A', 'Leonardo DiCaprio', 'Estadounidense', 49);
INSERT INTO ACTORES VALUES ('22222222B', 'Penélope Cruz', 'Española', 50);

INSERT INTO PAISES VALUES ('P1', 'España', 'Español');
INSERT INTO PAISES VALUES ('P2', 'Estados Unidos', 'Inglés');

INSERT INTO USUARIO VALUES ('U1', 'usuario1@email.com', SYSDATE);
INSERT INTO USUARIO VALUES ('U2', 'usuario2@email.com', SYSDATE);

INSERT INTO SUSCRIPCION VALUES ('S1', 'Premium', 15, 'U1');
INSERT INTO SUSCRIPCION VALUES ('S2', 'Básica', 8, 'U2');

INSERT INTO PERFILES VALUES ('PF1', 'Perfil Adulto', '1234', 30, 'U1');
INSERT INTO PERFILES VALUES ('PF2', 'Perfil Infantil', '0000', 10, 'U1');
INSERT INTO PERFILES VALUES ('PF3', 'Perfil Único', '9999', 40, 'U2');

INSERT INTO CONTENIDO VALUES ('CT1', 'Origen', 'Sueños dentro de sueños', 2010, 'Película', '12345678A');
INSERT INTO CONTENIDO VALUES ('CT2', 'Dolor y Gloria', 'Drama autobiográfico', 2019, 'Película', '87654321B');

INSERT INTO ACTUA VALUES ('CT1', '11111111A');
INSERT INTO ACTUA VALUES ('CT2', '22222222B');

INSERT INTO PERTENECE VALUES ('CT1', 'C1');
INSERT INTO PERTENECE VALUES ('CT2', 'C2');

INSERT INTO VISUALIZA VALUES ('CT1', 'P1');
INSERT INTO VISUALIZA VALUES ('CT1', 'P2');
INSERT INTO VISUALIZA VALUES ('CT2', 'P1');

INSERT INTO GUARDAN VALUES ('CT1', 'PF1');
INSERT INTO GUARDAN VALUES ('CT2', 'PF3');
