alter session set "_oracle_script"=true; 
create user PROYECTO identified by PROYECTO; 
GRANT CONNECT, RESOURCE, DBA TO PROYECTO;


CREATE TABLE CATEGORIAS(
	ID VARCHAR2(5),
	NOMBRE VARCHAR2(25),
	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID)
);

CREATE TABLE DIRECTOR(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(25),
	NACIONALIDAD VARCHAR2(25),
	EDAD NUMBER(3),
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI)
);

CREATE TABLE ACTORES(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(25),
	NACIONALIDAD VARCHAR2(25),
	EDAD NUMBER(3),
	CONSTRAINT PK_ACTORES PRIMARY KEY (DNI)
);

CREATE TABLE USUARIO(
	ID VARCHAR2(5),
	EMAIL VARCHAR2(25),
	FECHA_REGISTRO DATE,
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE PAISES(
	ID VARCHAR2(5),
	NOMBRE VARCHAR2(25),
	IDIAOMA VARCHAR2(20),
	CONSTRAINT PK_PAISES PRIMARY KEY (ID)
);
	
CREATE TABLE SUSCRIPCION(
	ID VARCHAR2(5),
	TIPO VARCHAR2(25),
	PRECIO NUMBER(5),
	ID_USU VARCHAR2(5),
	CONSTRAINT PK_SUSCRIPCION PRIMARY KEY (ID),
	CONSTRAINT FK1_SUSCRIPCION FOREIGN KEY (ID_USU) REFERENCES USUARIO (ID)
	
);

CREATE TABLE PERFILES(
	ID VARCHAR2(5),
	NOMBRE VARCHAR2(25),
	PIN VARCHAR2(5),
	EDAD NUMBER(3),
	ID_USU VARCHAR2(5),
	CONSTRAINT PK_PERFILES PRIMARY KEY (ID),
	CONSTRAINT FK1_PERFILES FOREIGN KEY (ID_USU) REFERENCES USUARIO (ID)
	
);

CREATE TABLE CONTENIDO(
	ID VARCHAR2(5),
	TITULO VARCHAR2(25),
	SINOPSIS VARCHAR2(30),
	ANIO NUMBER(4),
	TIPO VARCHAR2(20),
	DNI_DIRE VARCHAR2(9),
	CONSTRAINT PK_CONTENIDO PRIMARY KEY (ID),
	CONSTRAINT FK1_CONTENIDO FOREIGN KEY (DNI_DIRE) REFERENCES DIRECTOR (DNI)
	
);

CREATE TABLE GUARDAN(
	ID_CONTENIDO VARCHAR2(5),
	ID_PERFILES VARCHAR2(5),
	CONSTRAINT PK_GUARDAN PRIMARY KEY (ID_CONTENIDO, ID_PERFILES),
	CONSTRAINT FK1_GUARDAN FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_GUARDAN FOREIGN KEY (ID_PERFILES) REFERENCES PERFILES (ID)
);

CREATE TABLE ACTUA(
	ID_CONTENIDO VARCHAR2(5),
	DNI_ACTORES VARCHAR2(9),
	CONSTRAINT PK_ACTUA PRIMARY KEY (ID_CONTENIDO, DNI_ACTORES),
	CONSTRAINT FK1_ACTUA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_ACTUA FOREIGN KEY (DNI_ACTORES) REFERENCES ACTORES (DNI)
);

CREATE TABLE VISUALIZA(
	ID_CONTENIDO VARCHAR2(5),
	ID_PAISES VARCHAR2(5),
	CONSTRAINT PK_VISUALIZA PRIMARY KEY (ID_CONTENIDO, ID_PAISES),
	CONSTRAINT FK1_VISUALIZA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_VISUALIZA FOREIGN KEY (ID_PAISES) REFERENCES PAISES (ID)
);

CREATE TABLE PERTENECE(
	ID_CONTENIDO VARCHAR2(5),
	ID_CATEGORIAS VARCHAR2(5),
	CONSTRAINT PK_PERTENECE PRIMARY KEY (ID_CONTENIDO, ID_CATEGORIAS),
	CONSTRAINT FK1_PERTENECE FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_PERTENECE FOREIGN KEY (ID_CATEGORIAS) REFERENCES CATEGORIAS (ID)
)


	

