INSERT INTO CATEGORIAS VALUES ('C4', 'Ciencia Ficción');
INSERT INTO CATEGORIAS VALUES ('C5', 'Terror');
INSERT INTO CATEGORIAS VALUES ('C6', 'Romance');

INSERT INTO DIRECTOR VALUES ('33445566C', 'Denis Villeneuve', 'Canadiense', 56);
INSERT INTO DIRECTOR VALUES ('99887766D', 'Guillermo del Toro', 'Mexicana', 60);

INSERT INTO ACTORES VALUES ('33333333C', 'Ryan Gosling', 'Canadiense', 44);
INSERT INTO ACTORES VALUES ('44444444D', 'Jessica Chastain', 'Estadounidense', 47);

INSERT INTO PAISES VALUES ('P3', 'Canadá', 'Inglés');
INSERT INTO PAISES VALUES ('P4', 'México', 'Español');

INSERT INTO USUARIO VALUES ('U3', 'cinefilo@email.com', CURDATE());
INSERT INTO USUARIO VALUES ('U4', 'serieslover@email.com', CURDATE());

INSERT INTO SUSCRIPCION VALUES ('S3', 'Estándar', 12.00, 'U3');
INSERT INTO SUSCRIPCION VALUES ('S4', 'Premium', 15.00, 'U4');

INSERT INTO PERFILES VALUES ('PF4', 'Perfil Joven', '2222', 18, 'U3');
INSERT INTO PERFILES VALUES ('PF5', 'Perfil Familiar', '3333', 35, 'U4');

INSERT INTO CONTENIDO VALUES ('CT3', 'Blade Runner 2049', 'Futuro distópico y replicantes', 2017, 'Película', '33445566C');
INSERT INTO CONTENIDO VALUES ('CT4', 'El Laberinto del Fauno', 'Fantasía oscura en la posguerra', 2006, 'Película', '99887766D');

INSERT INTO ACTUA VALUES ('CT3', '33333333C');
INSERT INTO ACTUA VALUES ('CT4', '44444444D');

INSERT INTO PERTENECE VALUES ('CT3', 'C4');
INSERT INTO PERTENECE VALUES ('CT4', 'C5');

INSERT INTO VISUALIZA VALUES ('CT3', 'P3');
INSERT INTO VISUALIZA VALUES ('CT3', 'P1');
INSERT INTO VISUALIZA VALUES ('CT4', 'P4');

INSERT INTO GUARDAN VALUES ('CT3', 'PF4');
INSERT INTO GUARDAN VALUES ('CT4', 'PF5');
