/* create database PROYECTO; */

CREATE TABLE CATEGORIAS(
	ID VARCHAR(5),
	NOMBRE VARCHAR(25),
	CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID)
);

CREATE TABLE DIRECTOR(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(25),
	NACIONALIDAD VARCHAR(25),
	EDAD INT(3),
	CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI)
);

CREATE TABLE ACTORES(
	DNI VARCHAR(9),
	NOMBRE VARCHAR(25),
	NACIONALIDAD VARCHAR(25),
	EDAD INT(3),
	CONSTRAINT PK_ACTORES PRIMARY KEY (DNI)
);

CREATE TABLE USUARIO(
	ID VARCHAR(5),
	EMAIL VARCHAR(25),
	FECHA_REGISTRO DATE,
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

CREATE TABLE PAISES(
	ID VARCHAR(5),
	NOMBRE VARCHAR(25),
	IDIAOMA VARCHAR(20),
	CONSTRAINT PK_PAISES PRIMARY KEY (ID)
);
	
CREATE TABLE SUSCRIPCION(
	ID VARCHAR(5),
	TIPO VARCHAR(25),
	PRECIO INT(5),
	ID_USU VARCHAR(5),
	CONSTRAINT PK_SUSCRIPCION PRIMARY KEY (ID),
	CONSTRAINT FK1_SUSCRIPCION FOREIGN KEY (ID_USU) REFERENCES USUARIO (ID)
	
);

CREATE TABLE PERFILES(
	ID VARCHAR(5),
	NOMBRE VARCHAR(25),
	PIN VARCHAR(5),
	EDAD INT(3),
	ID_USU VARCHAR(5),
	CONSTRAINT PK_PERFILES PRIMARY KEY (ID),
	CONSTRAINT FK1_PERFILES FOREIGN KEY (ID_USU) REFERENCES USUARIO (ID)
	
);

CREATE TABLE CONTENIDO(
	ID VARCHAR(5),
	TITULO VARCHAR(25),
	SINOPSIS VARCHAR(30),
	ANIO INT(4),
	TIPO VARCHAR(20),
	DNI_DIRE VARCHAR(9),
	CONSTRAINT PK_CONTENIDO PRIMARY KEY (ID),
	CONSTRAINT FK1_CONTENIDO FOREIGN KEY (DNI_DIRE) REFERENCES DIRECTOR (DNI)
	
);

CREATE TABLE GUARDAN(
	ID_CONTENIDO VARCHAR(5),
	ID_PERFILES VARCHAR(5),
	CONSTRAINT PK_GUARDAN PRIMARY KEY (ID_CONTENIDO, ID_PERFILES),
	CONSTRAINT FK1_GUARDAN FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_GUARDAN FOREIGN KEY (ID_PERFILES) REFERENCES PERFILES (ID)
);

CREATE TABLE ACTUA(
	ID_CONTENIDO VARCHAR(5),
	DNI_ACTORES VARCHAR(9),
	CONSTRAINT PK_ACTUA PRIMARY KEY (ID_CONTENIDO, DNI_ACTORES),
	CONSTRAINT FK1_ACTUA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_ACTUA FOREIGN KEY (DNI_ACTORES) REFERENCES ACTORES (DNI)
);

CREATE TABLE VISUALIZA(
	ID_CONTENIDO VARCHAR(5),
	ID_PAISES VARCHAR(5),
	CONSTRAINT PK_VISUALIZA PRIMARY KEY (ID_CONTENIDO, ID_PAISES),
	CONSTRAINT FK1_VISUALIZA FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_VISUALIZA FOREIGN KEY (ID_PAISES) REFERENCES PAISES (ID)
);

CREATE TABLE PERTENECE(
	ID_CONTENIDO VARCHAR(5),
	ID_CATEGORIAS VARCHAR(5),
	CONSTRAINT PK_PERTENECE PRIMARY KEY (ID_CONTENIDO, ID_CATEGORIAS),
	CONSTRAINT FK1_PERTENECE FOREIGN KEY (ID_CONTENIDO) REFERENCES CONTENIDO (ID),
	CONSTRAINT FK2_PERTENECE FOREIGN KEY (ID_CATEGORIAS) REFERENCES CATEGORIAS (ID)
)

/* APARTADO NUEVAS RESTRICCIONES */

/* El precio de la suscripción debe ser mayor que 0 */

ALTER TABLE SUSCRIPCION
ADD CONSTRAINT CHK_SUSCRIPCION_PRECIO
CHECK (PRECIO > 0);

/* La edad de directores y actores debe ser mayor de 0 */

ALTER TABLE DIRECTOR
ADD CONSTRAINT CHK_DIRECTOR_EDAD
CHECK (EDAD > 0);

ALTER TABLE ACTORES
ADD CONSTRAINT CHK_ACTORES_EDAD
CHECK (EDAD > 0);

/* La edad de directores y actores debe ser mayor de 0 */

ALTER TABLE PERFILES
ADD CONSTRAINT CHK_PERFILES_PIN
CHECK (LENGTH(PIN) = 4);

/* El tipo de contenido solo puede ser "PELÍCULA" o "SERIE" */

ALTER TABLE CONTENIDO
ADD CONSTRAINT CHK_CONTENIDO_TIPO
CHECK (TIPO IN ('PELÍCULA', 'SERIE'));

/* APARTADO ENUNCIADOS DML */

/* Insertar un nuevo usuario en la plataforma. */

/* Actualizar el precio de una suscripción existente. */

/* Eliminar un perfil de usuario. */